### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [GrushaiNN/GrushaiNN.github.io#1]
Добрый день. Благодарю за проделанную работу. К сожалению, текущая реализация содержит ряд недостатков не позволяющих мне засчитать работу на данной итерации:

Репозиторий
**Нужно исправить**: README файл должен содержать номер версии (ненулевой), ссылку на проект (github pages) и заголовок отражающий назначение проекта.
**Нужно исправить**: отсутствуют git-теги отражающие номер версии. Создать их можно при помощи команды `git tag -a v0.0.1 -m "my first version"`
Обращаю внимание что теги по-умолчанию не публикуются при вызове команды `git push`
Для их публикации выполните команду `git push origin --tags`
Подробнее: https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%BC%D0%B5%D1%82%D0%BA%D0%B0%D0%BC%D0%B8
**Можно лучше**: Добавить .gitignore.
.gitignore должен содержать правила, исключающие попадание временных и\или системных файлов в репозиторий.

Регулярные выражения:
Имя:
Не проходят следующие корректные имена
`Ян` - имя может состоять из двух букв

Валидацию проходят следующие некорректные имена
`ЁлкаЁлка` - в каждой части имени может быть только одна заглавная буква

Email
**Нужно исправить** валидацию проходят следующие некорректные адреса почты
`_@site.ru` - имя ящика не может состоять только из спецсимволов
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол

**Можно лучше** валидацию проходят следующие некорректные адреса почты
my---mail@site.ru - адрес электронной почты, содержащий несколько символов '-' подряд является некорректным

Номер телефона:
**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.

+7(925 900-90-90
+7925900-90-90
+792590090-90
+7 (925) 900-90-90
+7 (925) 9009090
+7(925) 9009090
+7 (925)9009090
+7(925)9009090
+7 925 900-90-90

Адрес сайта
**Нужно исправить** валидацию проходят следующие некорректные адреса сайта:
https://mysite.23 - tld не может состоять из цифр 

**Можно лучше** валидацию проходят следующие некорректные адреса сайта:
https://999.999.999.999/ (у адреса ограничение: в ipv4 каждая часть адреса должна быть целым положительным числом и не больше 8 бит, те: 255)

**Comment by zlocate** [comment]
Добрый день. К сожалению, текущая формулировка задания не совсем точна. Мы работаем над этим и постараемся в следующей версии задания добавить данные негативные кейсы к чек-листам, дабы не возникало неоднозначных трактовок.

В текущем листе требований для ревьюверов данные номера находятся в списке запрещенных. 
Поскольку мы действуем в рамках требований чек-листов я вынужден попросить вас исправить данные кейсы

**Comment by zlocate** [comment]
**Нужно исправить** ссылка в README должна вести на непосредственно страницу на Github Pages. 
Т.е быть следующей: https://grushainn.github.io/

**Нужно исправить** правильное имя файла .gitignore не содержит расширения. 
К сожалению, в текущей версии правила из gitignore не будут применены из-за того что файл не будет учтен

**Comment by zlocate** [comment]
Добрый день. Благодарю вас за проделанную работу. 
К сожалению, в текущей версии сохраняются проблемы, требующие проработки:

Регулярные выражения:
Email:
some@mail.yandex.ru - доменное имя может включать в себя поддомены
some@x.com - доменное имя может состоять из одного символа
x@gmail.com - имя ящика может состоять из одного символа
some-extra-long-name@some.extra.long.domain.name - доменное имя может включать в себя произвольное количество поддоменов

Нужно исправить: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.

+7(925 900-90-90
+7925900-90-90
+792590090-90
+7 (925) 900-90-90
+7 (925) 9009090
+7(925) 9009090
+7 (925)9009090
+7(925)9009090
+7 925 900-90-90

**Comment by GrushaiNN** [comment]
Доброго дня! 
Таки очень неприятно получать замечания заранее не обозначенные условиями задачи!
Я таким образом могу вечно сдавать этот проект, ибо не имею понятия какие именно условия валидности прописаны в Ваших чек-листах!

**Comment by zlocate** [comment]
> Доброго дня!
> Таки очень неприятно получать замечания заранее не обозначенные условиями задачи!
> Я таким образом могу вечно сдавать этот проект, ибо не имею понятия какие именно условия валидности прописаны в Ваших чек-листах!

Частично соглашусь с вами. Рассинхрон в требованиях зло - однако в задании четко указано какие маски номеров должны проходить, все что не подходит под них - считается в данном случае некорректным.
С толку может сбить фраза "могут содержаться пробелы", это да.


З.Ы Мы не злодеи и не стараемся никого рубить зазря и выискивать несущественные или отсутствующие у студентов недостатки.

З.Ы.Ы К тому же это наглядный кейс когда нужно оптимиально реализовать валидацию нескольких строго сформированных форматов на мой взгляд

**Comment by zlocate** [comment]
Дабы не быть голословным - вопрос на обсуждении вынесен мною
http://i.imgur.com/yMOSPvw.png

**Comment by zlocate** [comment]
**Можно лучше**
Квартификатор `+`означает «один или более». То же самое, что и {1,}.

**Comment by zlocate** [comment]
Добрый день. Работа принята. 
Желаю вам успехов в дальнейшем изучении материалов курса :)

**Comment by GrushaiNN** [comment]
> Добрый день. Работа принята.
> Желаю вам успехов в дальнейшем изучении материалов курса :)

Спасибо большое! )) 

З.Ы. Я ни в коем случае не считаю никого из вас злодеями )) Просто не ожидал наткнуться на такое ))
